name: 📦 Build 

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'astro/prod'
          persist-credentials: true

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'markdown/prod'
          path: 'src/content/wiki'

      - name: Install, build, and upload your site output
        uses: withastro/action@v4
        with:
            package-manager: pnpm@latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4